### ISSUE TITLE
403 Error

### ISSUE THREAD

**Issue by robinhaggqvist** [marple-newsrobot/allabolag#4]
Seems like we have a issue requesting now. 
My best guess is user agent since you can click the link in browser

HTTPError: 403 Client Error: Forbidden for url: https://www.allabolag.se/5592835168

`/GET https://www.allabolag.se/5592835168
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
/tmp/ipykernel_46043/1296122468.py in <module>
      4 
      5 # show all available data about the company in a raw...
----> 6 print(company.raw_data)
      7 
      8 # ...or cleaned format

~/.local/lib/python3.10/site-packages/allabolag/company.py in raw_data(self)
     27         """
     28         data = {}
---> 29         data.update(self.overview_data)
     30         data.update(self.activity_data)
     31         data.update(self.accounts_data)

~/.local/lib/python3.10/site-packages/allabolag/company.py in overview_data(self)
     43         """
     44         if self._overview_data == {}:
---> 45             s = self._get_soup()
     46             data = {
     47                 "Namn": s.select_one("h1").text.strip(),

~/.local/lib/python3.10/site-packages/allabolag/company.py in _get_soup(self, endpoint)
    155         print("/GET {}".format(url))
    156         r = requests.get(url)
--> 157         r.raise_for_status()
    158         return BeautifulSoup(r.content, "html.parser")

~/.local/lib/python3.10/site-packages/requests/models.py in raise_for_status(self)
   1022 
   1023         if http_error_msg:
-> 1024             raise HTTPError(http_error_msg, response=self)
   1025 
   1026     def close(self):

HTTPError: 403 Client Error: Forbidden for url: https://www.allabolag.se/5592835168`

**Comment by robinhaggqvist** [comment]
Dont seem to be an issie. Maybe it was error on allabolag side.

**Comment by rotsee** [comment]
An older version did indeed use a UA string that was probably blocked. We haven't seen any 403's in the last couple of months though
